version: '2'
services:
    smartcounter-app:
        image: smartcounter
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://smartcounter-mysql:3306/smartcounter?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    smartcounter-mysql:
        extends:
            file: mysql.yml
            service: smartcounter-mysql
